class DockerfileGenerator
  # Generates a production Dockerfile (and .dockerignore) for a detected app.
  #
  # Every template follows the same rules:
  #   * base images pinned to the runtime line detected from the repo
  #     (.ruby-version, Gemfile.lock, .nvmrc, engines.node, requires-python, go.mod ...)
  #   * multi-stage: build tooling never ships in the runtime image
  #   * runs as a non-root user
  #   * listens on $PORT (defaults to the detected port) on 0.0.0.0
  #   * installs from the lockfile when there is one (npm ci, yarn --frozen-lockfile,
  #     pnpm --frozen-lockfile, bun --frozen-lockfile, BUNDLE_DEPLOYMENT, uv --frozen ...)
  #
  # Output is a pure function of the detection result — no timestamps, no
  # filesystem-order dependence — so the same repo always yields the same
  # Dockerfile (golden-file tested in spec/fixtures/repos/*/expected.Dockerfile).
  PreviewDetection = Struct.new(:framework, :metadata, :port)

  NGINX_IMAGE   = "nginxinc/nginx-unprivileged:1.27-alpine".freeze
  DISTROLESS    = "gcr.io/distroless/static-debian12:nonroot".freeze

  # Returns the Dockerfile content for a given framework and metadata hash
  # without touching the filesystem — used for preview in the UI.
  def self.preview(framework, metadata = {})
    metadata  = (metadata || {}).to_h.stringify_keys
    detection = PreviewDetection.new(framework, metadata, metadata["port"] || default_port(framework))
    new(nil, detection).dockerfile
  end

  def self.default_port(framework)
    Analysis::DirectoryDetector::DEFAULT_PORTS.fetch(framework.to_s, 8080)
  end

  def initialize(repo_path, detection)
    @repo_path = repo_path
    @detection = detection
  end

  # Writes a Dockerfile into the app directory (the repo root, or the
  # detected root_dir inside a monorepo). No-ops if one already exists.
  # Also writes a .dockerignore when missing. Returns the Dockerfile path —
  # its directory is the Docker build context.
  def call
    dockerfile_path = File.join(app_path, "Dockerfile")
    return dockerfile_path if File.exist?(dockerfile_path)

    content = dockerfile
    raise "No Dockerfile template for framework: #{@detection.framework}" if content.nil?

    File.write(dockerfile_path, content)
    generate_dockerignore
    dockerfile_path
  end

  # The Dockerfile text, or nil when the framework has no template
  # ("docker" repos bring their own).
  def dockerfile
    template_for(@detection.framework)
  end

  # The .dockerignore text for this framework.
  def dockerignore
    dockerignore_content
  end

  private

  def app_path
    return @repo_path unless @detection.respond_to?(:app_path)

    @detection.app_path(@repo_path)
  end

  def m(key)
    (@detection.metadata || {})[key]
  end

  def port
    (@detection.port || self.class.default_port(@detection.framework)).to_i
  end

  def template_for(framework)
    case framework
    when "rails"   then rails_template
    when "node"    then node_template
    when "nextjs"  then m("next_export") ? static_template(build_tool: "next", output_dir: "out") : nextjs_template
    when "fastapi", "flask", "django", "python" then python_template(framework)
    when "static"  then static_template
    when "go"      then go_template
    when "bun"     then bun_template
    when "elixir"  then elixir_template
    else                nil # "docker" framework already has a Dockerfile
    end
  end

  def header(name)
    <<~TEXT.chomp
      # syntax=docker/dockerfile:1
      # Generated by Anchor for a #{name} app. Commit your own Dockerfile to take over.
    TEXT
  end

  # Joins template sections, dropping empty ones, with one blank line between.
  def assemble(*sections)
    sections.flatten.compact.map(&:strip).reject(&:empty?).join("\n\n") + "\n"
  end

  # ── Rails ──────────────────────────────────────────────────────────── #

  RAILS_DB_PACKAGES = {
    "postgresql" => { build: "libpq-dev", runtime: "libpq5" },
    "mysql"      => { build: "default-libmysqlclient-dev", runtime: "libmariadb3" },
    "sqlite"     => { build: "libsqlite3-dev", runtime: "libsqlite3-0" }
  }.freeze

  def rails_template
    ruby_version = m("ruby_version") || Analysis::RuntimeVersions::DEFAULTS["ruby"]
    has_lock     = m("bundler_lock")
    db           = RAILS_DB_PACKAGES[m("database_adapter")]
    js           = m("has_package_json")
    rails_ver    = m("rails_version")

    runtime_pkgs = [ "curl", "libjemalloc2", db&.dig(:runtime) ].compact.join(" ")
    build_pkgs   = [ "build-essential", "git", "libyaml-dev", "pkg-config", db&.dig(:build), (js ? "nodejs npm" : nil) ].compact.join(" ")

    env = [ "RAILS_ENV=production", "BUNDLE_PATH=/usr/local/bundle", "BUNDLE_WITHOUT=development:test" ]
    env << "BUNDLE_DEPLOYMENT=1" if has_lock
    env += [ "RAILS_LOG_TO_STDOUT=true", "RAILS_SERVE_STATIC_FILES=true" ]

    base = <<~DOCKERFILE
      # ── Base: runtime libraries shared by all stages ────────────────────────
      FROM ruby:#{ruby_version}-slim AS base

      WORKDIR /rails

      RUN apt-get update -qq && \\
          apt-get install --no-install-recommends -y #{runtime_pkgs} && \\
          rm -rf /var/lib/apt/lists /var/cache/apt/archives

      ENV #{env.join(" \\\n    ")}
    DOCKERFILE

    bundler = m("bundler_version") ? "RUN gem install bundler -v #{m('bundler_version')} --no-document\n\n" : ""
    install = <<~DOCKERFILE
      # ── Build: gems, JS and assets ──────────────────────────────────────────
      FROM base AS build

      RUN apt-get update -qq && \\
          apt-get install --no-install-recommends -y #{build_pkgs} && \\
          rm -rf /var/lib/apt/lists /var/cache/apt/archives

      #{bundler}#{has_lock ? 'COPY Gemfile Gemfile.lock ./' : 'COPY Gemfile ./'}
      RUN bundle install && \\
          rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git
    DOCKERFILE

    js_install = js ? node_install_lines(prod_only: false) : nil

    build_steps = [ "COPY . ." ]
    build_steps << "RUN bundle exec bootsnap precompile app/ lib/" if m("has_bootsnap")
    if m("assets") != false
      build_steps << "# SECRET_KEY_BASE_DUMMY lets assets compile without real credentials.\n" \
                     "RUN SECRET_KEY_BASE_DUMMY=1 bundle exec rails assets:precompile"
    end

    # /up exists from Rails 7.1; unknown versions (no lockfile) get it too.
    healthcheck = if rails_ver.nil? || Analysis::RuntimeVersions.compare(rails_ver, "7.1") >= 0
      "HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \\\n  CMD curl -fsS http://127.0.0.1:${PORT}/up || exit 1"
    end

    cmd = if m("has_puma_config") == false
      %(CMD ["sh", "-c", "exec bundle exec rails server -b 0.0.0.0 -p ${PORT}"])
    else
      # config/puma.rb generated by Rails binds 0.0.0.0:$PORT.
      %(CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"])
    end

    runtime = <<~DOCKERFILE
      # ── Runtime: non-root, only what the app needs ──────────────────────────
      FROM base

      RUN groupadd --system --gid 1000 rails && \\
          useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash

      COPY --from=build "${BUNDLE_PATH}" "${BUNDLE_PATH}"
      COPY --from=build --chown=rails:rails /rails /rails

      USER 1000:1000

      ENV PORT=#{port}
      EXPOSE #{port}
    DOCKERFILE

    assemble(header("Rails"), base, install, js_install, build_steps.join("\n"), runtime, healthcheck, cmd)
  end

  # ── Node.js (Express, Fastify, Nest, Remix, Nuxt ...) ──────────────── #

  def node_image
    "node:#{m('node_version') || Analysis::RuntimeVersions::DEFAULTS['node']}-alpine"
  end

  # Lockfile the Dockerfile can rely on (a workspace-root lockfile is outside
  # the build context, so it doesn't count).
  def usable_lockfile
    return nil if m("workspace_lockfile")

    m("lockfile") || (m("has_lock_file") ? default_lockfile : nil)
  end

  def default_lockfile
    { "npm" => "package-lock.json", "yarn" => "yarn.lock", "pnpm" => "pnpm-lock.yaml", "bun" => "bun.lock" }[package_manager]
  end

  def package_manager
    m("package_manager") || "npm"
  end

  def install_command(prod_only:)
    lock = usable_lockfile
    case package_manager
    when "pnpm"
      cmd = lock ? "pnpm install --frozen-lockfile" : "pnpm install"
      "corepack enable && #{cmd}#{' --prod' if prod_only}"
    when "yarn"
      if m("yarn_berry")
        "corepack enable && yarn install#{' --immutable' if lock}"
      else
        "yarn install#{' --frozen-lockfile' if lock}#{' --production' if prod_only}"
      end
    when "bun"
      "npm install -g bun@#{m('bun_version') || '1'} && bun install#{' --frozen-lockfile' if lock}#{' --production' if prod_only}"
    else
      "#{lock ? 'npm ci' : 'npm install'}#{' --omit=dev' if prod_only}"
    end
  end

  # corepack must be enabled in every stage that calls pnpm or yarn berry.
  def corepack_prefix
    package_manager == "pnpm" || (package_manager == "yarn" && m("yarn_berry")) ? "corepack enable && " : ""
  end

  def prune_command
    case package_manager
    when "pnpm" then "corepack enable && pnpm prune --prod"
    when "npm"  then "npm prune --omit=dev"
    end
  end

  # bun isn't installed in later node stages, and npm runs any script.
  def run_script(name)
    case package_manager
    when "pnpm" then "#{corepack_prefix}pnpm run #{name}"
    when "yarn" then "#{corepack_prefix}yarn run #{name}"
    else             "npm run #{name}"
    end
  end

  def copy_manifests
    files = [ "package.json", usable_lockfile ].compact
    files << ".yarnrc.yml*" if package_manager == "yarn" && m("yarn_berry")
    "COPY #{files.join(' ')} ./"
  end

  # `mkdir -p node_modules` keeps the later `COPY --from=deps /app/node_modules`
  # working for apps with no dependencies, where the install creates nothing.
  def node_install_lines(prod_only:)
    "#{copy_manifests}\nRUN #{install_command(prod_only: prod_only)} && mkdir -p node_modules"
  end

  def node_template
    build   = m("build_script")
    nuxt    = m("node_framework") == "nuxt"
    start   = m("start_script")
    main    = m("main") || "index.js"

    deps = <<~DOCKERFILE
      # ── Dependencies ────────────────────────────────────────────────────────
      FROM #{node_image} AS deps

      WORKDIR /app

      #{node_install_lines(prod_only: !build)}
    DOCKERFILE

    build_stage = if build
      # Nuxt ships only .output, so there is nothing to prune.
      prune = nuxt ? nil : prune_command
      <<~DOCKERFILE
        # ── Build ───────────────────────────────────────────────────────────────
        FROM #{node_image} AS build

        WORKDIR /app

        COPY --from=deps /app/node_modules ./node_modules
        COPY . .
        RUN #{run_script('build')}#{prune ? "\nRUN #{prune}" : ''}
      DOCKERFILE
    end

    copy = if nuxt && build
      "COPY --from=build --chown=node:node /app/.output ./.output"
    elsif build
      "COPY --from=build --chown=node:node /app ./"
    else
      "COPY --from=deps --chown=node:node /app/node_modules ./node_modules\nCOPY --chown=node:node . ."
    end

    cmd = if nuxt && build
      %(CMD ["node", ".output/server/index.mjs"])
    elsif start
      %(CMD ["npm", "start"])
    else
      %(CMD ["node", "#{main}"])
    end

    runtime = <<~DOCKERFILE
      # ── Runtime ─────────────────────────────────────────────────────────────
      FROM #{node_image} AS runner

      WORKDIR /app

      ENV NODE_ENV=production \\
          HOST=0.0.0.0 \\
          PORT=#{port}

      #{copy}

      USER node

      EXPOSE #{port}
    DOCKERFILE

    assemble(header(nuxt ? "Nuxt" : "Node.js"), deps, build_stage, runtime, cmd)
  end

  # ── Next.js ────────────────────────────────────────────────────────── #

  def nextjs_template
    standalone = m("next_standalone")

    deps = <<~DOCKERFILE
      # ── Dependencies ────────────────────────────────────────────────────────
      FROM #{node_image} AS deps

      RUN apk add --no-cache libc6-compat

      WORKDIR /app

      #{node_install_lines(prod_only: false)}
    DOCKERFILE

    builder = <<~DOCKERFILE
      # ── Build ───────────────────────────────────────────────────────────────
      FROM #{node_image} AS builder

      WORKDIR /app

      COPY --from=deps /app/node_modules ./node_modules
      COPY . .

      ENV NEXT_TELEMETRY_DISABLED=1
      RUN #{run_script('build')}
    DOCKERFILE

    copy, cmd =
      if standalone
        lines = []
        lines << "COPY --from=builder --chown=node:node /app/public ./public" unless m("has_public_dir") == false
        lines << "# output: \"standalone\" bundles only the files the server needs."
        lines << "COPY --from=builder --chown=node:node /app/.next/standalone ./"
        lines << "COPY --from=builder --chown=node:node /app/.next/static ./.next/static"
        [ lines.join("\n"), %(CMD ["node", "server.js"]) ]
      else
        [ "# Set output: \"standalone\" in next.config for a much smaller image.\n" \
         "COPY --from=builder --chown=node:node /app ./",
         %(CMD ["node_modules/.bin/next", "start", "-H", "0.0.0.0"]) ]
      end

    runner = <<~DOCKERFILE
      # ── Runtime ─────────────────────────────────────────────────────────────
      FROM #{node_image} AS runner

      WORKDIR /app

      ENV NODE_ENV=production \\
          NEXT_TELEMETRY_DISABLED=1 \\
          HOSTNAME=0.0.0.0 \\
          PORT=#{port}

      #{copy}

      USER node

      EXPOSE #{port}
    DOCKERFILE

    assemble(header("Next.js"), deps, builder, runner, cmd)
  end

  # ── Bun ────────────────────────────────────────────────────────────── #

  def bun_template
    image   = "oven/bun:#{m('bun_version') || '1'}-alpine"
    build   = m("build_script")
    frozen  = m("has_lock_file") == false ? "" : " --frozen-lockfile"
    start   = m("start_script") ? %(CMD ["bun", "run", "start"]) : %(CMD ["bun", "run", "#{m('main') || 'index.ts'}"])

    deps = <<~DOCKERFILE
      # ── Dependencies ────────────────────────────────────────────────────────
      FROM #{image} AS deps

      WORKDIR /app

      COPY package.json bun.lock* bun.lockb* ./
      RUN bun install#{frozen}#{' --production' unless build} && mkdir -p node_modules
    DOCKERFILE

    build_stage = if build
      <<~DOCKERFILE
        # ── Build ───────────────────────────────────────────────────────────────
        FROM #{image} AS build

        WORKDIR /app

        COPY --from=deps /app/node_modules ./node_modules
        COPY . .
        RUN bun run build
      DOCKERFILE
    end

    copy = build ? "COPY --from=build --chown=bun:bun /app ./" : "COPY --from=deps --chown=bun:bun /app/node_modules ./node_modules\nCOPY --chown=bun:bun . ."

    runtime = <<~DOCKERFILE
      # ── Runtime ─────────────────────────────────────────────────────────────
      FROM #{image}

      WORKDIR /app

      ENV NODE_ENV=production \\
          PORT=#{port}

      #{copy}

      USER bun

      EXPOSE #{port}
    DOCKERFILE

    assemble(header("Bun"), deps, build_stage, runtime, start)
  end

  # ── Python (FastAPI, Flask, Django, plain) ─────────────────────────── #

  def python_template(framework)
    version = m("python_version") || Analysis::RuntimeVersions::DEFAULTS["python"]
    image   = "python:#{version}-slim"

    build = <<~DOCKERFILE
      # ── Build: dependencies into a virtualenv ───────────────────────────────
      FROM #{image} AS build

      ENV PYTHONDONTWRITEBYTECODE=1 \\
          PYTHONUNBUFFERED=1 \\
          PIP_DISABLE_PIP_VERSION_CHECK=1 \\
          VIRTUAL_ENV=/opt/venv \\
          PATH="/opt/venv/bin:$PATH"

      WORKDIR /app

      RUN python -m venv /opt/venv

      #{python_install_steps}
    DOCKERFILE

    extra = python_server_packages(framework)
    build += "RUN pip install --no-cache-dir #{extra.join(' ')}\n" if extra.any?

    collectstatic = if framework == "django" && m("collectstatic")
      "# Throwaway key: collectstatic imports settings but never signs anything.\n" \
      "RUN SECRET_KEY=collectstatic-only DJANGO_SECRET_KEY=collectstatic-only python manage.py collectstatic --noinput"
    end

    settings = django_settings_module if framework == "django"
    env = [ "PYTHONDONTWRITEBYTECODE=1", "PYTHONUNBUFFERED=1", "VIRTUAL_ENV=/opt/venv", %(PATH="/opt/venv/bin:$PATH"), "PORT=#{port}" ]
    env << "DJANGO_SETTINGS_MODULE=#{settings}" if settings

    runtime = <<~DOCKERFILE
      # ── Runtime: non-root, venv + source only ───────────────────────────────
      FROM #{image}

      ENV #{env.join(" \\\n    ")}

      WORKDIR /app

      RUN groupadd --system --gid 1000 app && \\
          useradd --system --uid 1000 --gid app --no-create-home app

      COPY --from=build /opt/venv /opt/venv
      COPY --chown=app:app . .
    DOCKERFILE

    tail = <<~DOCKERFILE
      USER app

      EXPOSE #{port}
    DOCKERFILE

    label = { "fastapi" => "FastAPI", "flask" => "Flask", "django" => "Django", "python" => "Python" }[framework]
    assemble(header(label), build, runtime, collectstatic, tail, python_cmd(framework))
  end

  def python_install_steps
    case m("package_manager")
    when "uv"
      <<~STEPS
        RUN /usr/local/bin/python -m pip install --no-cache-dir "uv>=0.5,<1"
        ENV UV_PROJECT_ENVIRONMENT=/opt/venv \\
            UV_COMPILE_BYTECODE=1 \\
            UV_LINK_MODE=copy
        COPY pyproject.toml uv.lock ./
        RUN uv sync --frozen --no-dev --no-install-project
      STEPS
    when "poetry"
      <<~STEPS
        RUN python -m venv /opt/poetry && \\
            /opt/poetry/bin/pip install --no-cache-dir "poetry>=1.8,<3"
        ENV POETRY_VIRTUALENVS_CREATE=false \\
            POETRY_NO_INTERACTION=1
        COPY pyproject.toml poetry.lock ./
        RUN /opt/poetry/bin/poetry install --only main --no-root
      STEPS
    when "pipenv"
      <<~STEPS
        RUN python -m venv /opt/pipenv && \\
            /opt/pipenv/bin/pip install --no-cache-dir pipenv
        COPY Pipfile Pipfile.lock* ./
        RUN /opt/pipenv/bin/pipenv requirements > /tmp/requirements.txt && \\
            pip install --no-cache-dir -r /tmp/requirements.txt
      STEPS
    when "pip-pyproject"
      <<~STEPS
        COPY . .
        RUN pip install --no-cache-dir .
      STEPS
    else
      <<~STEPS
        COPY requirements.txt ./
        RUN pip install --no-cache-dir -r requirements.txt
      STEPS
    end
  end

  # Production servers the start command needs but the app didn't declare.
  def python_server_packages(framework)
    return [] if m("procfile_web")

    case framework
    when "fastapi" then m("has_uvicorn") ? [] : [ "uvicorn" ]
    when "flask", "django" then m("has_gunicorn") ? [] : [ "gunicorn" ]
    else []
    end
  end

  def django_settings_module
    m("settings_module") || m("wsgi_module")&.sub(/\.wsgi\z/, ".settings")
  end

  def python_cmd(framework)
    if (web = m("procfile_web"))
      return %(CMD ["sh", "-c", #{("exec " + web.delete_prefix('exec ')).to_json}])
    end

    case framework
    when "fastapi"
      app = m("asgi_app") || "#{File.basename(m('entry_point') || 'main.py', '.py')}:app"
      %(CMD ["sh", "-c", "exec uvicorn #{app} --host 0.0.0.0 --port ${PORT} --proxy-headers"])
    when "flask"
      app = m("wsgi_app") || "#{File.basename(m('entry_point') || 'app.py', '.py')}:app"
      %(CMD ["sh", "-c", "exec gunicorn --bind 0.0.0.0:${PORT} --workers 2 #{app}"])
    when "django"
      wsgi = m("wsgi_module") || "wsgi"
      wsgi = "#{wsgi}:application" unless wsgi.include?(":")
      %(CMD ["sh", "-c", "exec gunicorn --bind 0.0.0.0:${PORT} --workers 2 #{wsgi}"])
    else
      %(CMD ["python", "#{m('entry_point') || 'app.py'}"])
    end
  end

  # ── Static sites (plain HTML or a Vite/CRA/Astro/Next export build) ── #

  def static_template(build_tool: m("build_tool"), output_dir: m("output_dir"))
    build_stage = if build_tool
      <<~DOCKERFILE
        # ── Build ───────────────────────────────────────────────────────────────
        FROM #{node_image} AS build

        WORKDIR /app

        #{node_install_lines(prod_only: false)}

        COPY . .
        RUN #{run_script('build')}
      DOCKERFILE
    end

    source = if build_tool
      "COPY --from=build /app/#{output_dir || 'dist'} /usr/share/nginx/html"
    else
      "COPY #{output_dir ? "#{output_dir}/" : '.'} /usr/share/nginx/html"
    end

    fallback = build_tool ? "/index.html" : "=404"
    # The unprivileged nginx image can't bind ports below 1024.
    listen   = port < 1024 ? 8080 : port
    runtime = <<~DOCKERFILE
      # ── Runtime: unprivileged nginx listening on $PORT ──────────────────────
      FROM #{NGINX_IMAGE}

      USER root
      RUN mkdir -p /etc/nginx/templates && \\
          printf '%s\\n' \\
            'server {' \\
            '  listen ${PORT};' \\
            '  server_name _;' \\
            '  server_tokens off;' \\
            '  root /usr/share/nginx/html;' \\
            '  index index.html;' \\
            '  location / { try_files $uri $uri/ #{fallback}; }' \\
            '}' > /etc/nginx/templates/default.conf.template
      USER 101

      #{source}

      ENV PORT=#{listen}
      EXPOSE #{listen}

      CMD ["nginx", "-g", "daemon off;"]
    DOCKERFILE

    assemble(header(build_tool ? "static (#{build_tool})" : "static"), build_stage, runtime)
  end

  # ── Go ─────────────────────────────────────────────────────────────── #

  def go_template
    go_version = m("go_version") || Analysis::RuntimeVersions::DEFAULTS["go"]
    main_pkg   = m("main_package") || "."

    <<~DOCKERFILE
      #{header('Go')}

      # ── Build: static binary ────────────────────────────────────────────────
      FROM golang:#{go_version}-alpine AS build

      WORKDIR /src

      COPY go.mod go.sum* ./
      RUN go mod download

      COPY . .
      RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/app #{main_pkg}

      # ── Runtime: distroless, non-root ───────────────────────────────────────
      FROM #{DISTROLESS}

      COPY --from=build /out/app /app

      ENV PORT=#{port}
      EXPOSE #{port}

      USER nonroot:nonroot

      ENTRYPOINT ["/app"]
    DOCKERFILE
  end

  # ── Elixir / Phoenix ───────────────────────────────────────────────── #

  def elixir_template
    app_name = m("mix_project") || "app"
    phoenix  = m("has_phoenix")

    builder_image, runner_image = Analysis::RuntimeVersions::ELIXIR_IMAGES.fetch(
      m("elixir_version").to_s, Analysis::RuntimeVersions::ELIXIR_IMAGES.fetch(Analysis::RuntimeVersions::DEFAULTS["elixir"])
    )
    assets = phoenix && m("has_assets") != false ? "RUN mix assets.deploy\n" : ""
    config = m("has_config") == false ? "" : "# Compile-time config must be present before dependencies compile.\nCOPY config config\n"
    env = [ "MIX_ENV=prod", "PORT=#{port}" ]
    env.unshift("PHX_SERVER=true") if phoenix

    <<~DOCKERFILE
      #{header(phoenix ? 'Phoenix' : 'Elixir')}

      # ── Build: compile a release ────────────────────────────────────────────
      FROM #{builder_image} AS build

      RUN apk add --no-cache build-base git

      WORKDIR /app

      ENV MIX_ENV=prod

      RUN mix local.hex --force && mix local.rebar --force

      COPY mix.exs mix.lock* ./
      RUN mix deps.get --only prod

      #{config}RUN mix deps.compile

      COPY . .
      #{assets}RUN mix compile && mix release

      # ── Runtime: release only, non-root ─────────────────────────────────────
      FROM #{runner_image}

      RUN apk add --no-cache libstdc++ openssl ncurses-libs

      WORKDIR /app

      RUN addgroup -g 1000 elixir && adduser -u 1000 -G elixir -s /bin/sh -D elixir

      COPY --from=build --chown=elixir:elixir /app/_build/prod/rel/#{app_name} ./

      USER elixir:elixir

      ENV #{env.join(" \\\n    ")}
      EXPOSE #{port}

      CMD ["bin/#{app_name}", "start"]
    DOCKERFILE
  end

  # ------------------------------------------------------------------ #
  # .dockerignore                                                       #
  # ------------------------------------------------------------------ #

  def generate_dockerignore
    return unless @repo_path

    ignore_path = File.join(app_path, ".dockerignore")
    return if File.exist?(ignore_path)

    File.write(ignore_path, dockerignore_content)
  end

  COMMON_IGNORES = %w[
    .git .github .gitlab-ci.yml .circleci .dockerignore Dockerfile* docker-compose*.yml compose*.yml
    .env .env.* !.env.example !.env.sample .DS_Store *.log .idea .vscode coverage
  ].freeze

  FRAMEWORK_IGNORES = {
    "rails"  => %w[/log/* /tmp/* !/log/.keep !/tmp/.keep /storage/* /public/assets /node_modules
                   /vendor/bundle /.bundle /config/master.key /config/credentials/*.key /app/assets/builds/*],
    "node"   => %w[node_modules .next .nuxt .output .turbo npm-debug.log* yarn-error.log*],
    "nextjs" => %w[node_modules .next out .turbo npm-debug.log* yarn-error.log*],
    "bun"    => %w[node_modules .turbo],
    "python" => %w[__pycache__ *.py[cod] .venv venv .pytest_cache .mypy_cache .ruff_cache .tox *.egg-info],
    "go"     => %w[/bin vendor],
    "elixir" => %w[_build deps .elixir_ls],
    "static" => %w[node_modules]
  }.freeze

  def dockerignore_content
    family = case @detection.framework
    when "fastapi", "flask", "django", "python" then "python"
    else @detection.framework.to_s
    end
    extra = FRAMEWORK_IGNORES.fetch(family, [])
    extra += %w[dist build] if family == "static" && m("build_tool")

    lines = [ "# Generated by Anchor — keeps secrets and local artifacts out of the build context." ]
    lines += COMMON_IGNORES
    lines += extra
    lines.join("\n") + "\n"
  end
end
