# syntax=docker/dockerfile:1
# Generated by Anchor for a Go app. Commit your own Dockerfile to take over.

# ── Build: static binary ────────────────────────────────────────────────
FROM golang:1.23-alpine AS build

WORKDIR /src

COPY go.mod go.sum* ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/app ./cmd/server

# ── Runtime: distroless, non-root ───────────────────────────────────────
FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=build /out/app /app

ENV PORT=8080
EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/app"]
