# syntax=docker/dockerfile:1
# Generated by Anchor for a Bun app. Commit your own Dockerfile to take over.

# ── Dependencies ────────────────────────────────────────────────────────
FROM oven/bun:1-alpine AS deps

WORKDIR /app

COPY package.json bun.lock* bun.lockb* ./
RUN bun install --frozen-lockfile --production && mkdir -p node_modules

# ── Runtime ─────────────────────────────────────────────────────────────
FROM oven/bun:1-alpine

WORKDIR /app

ENV NODE_ENV=production \
    PORT=3000

COPY --from=deps --chown=bun:bun /app/node_modules ./node_modules
COPY --chown=bun:bun . .

USER bun

EXPOSE 3000

CMD ["bun", "run", "start"]
