# syntax=docker/dockerfile:1
# Generated by Anchor for a FastAPI app. Commit your own Dockerfile to take over.

# ── Build: dependencies into a virtualenv ───────────────────────────────
FROM python:3.12-slim AS build

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:$PATH"

WORKDIR /app

RUN python -m venv /opt/venv

RUN /usr/local/bin/python -m pip install --no-cache-dir "uv>=0.5,<1"
ENV UV_PROJECT_ENVIRONMENT=/opt/venv \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

# ── Runtime: non-root, venv + source only ───────────────────────────────
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:$PATH" \
    PORT=8000

WORKDIR /app

RUN groupadd --system --gid 1000 app && \
    useradd --system --uid 1000 --gid app --no-create-home app

COPY --from=build /opt/venv /opt/venv
COPY --chown=app:app . .

USER app

EXPOSE 8000

CMD ["sh", "-c", "exec uvicorn app.main:api --host 0.0.0.0 --port ${PORT} --proxy-headers"]
