source "https://rubygems.org"

ruby file: ".ruby-version"

gem "rails", "~> 8.0.2"
gem "propshaft"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
