# syntax=docker/dockerfile:1
# Generated by Anchor for a Flask app. Commit your own Dockerfile to take over.

# ── Build: dependencies into a virtualenv ───────────────────────────────
FROM python:3.11-slim AS build

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:$PATH"

WORKDIR /app

RUN python -m venv /opt/venv

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# ── Runtime: non-root, venv + source only ───────────────────────────────
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:$PATH" \
    PORT=5000

WORKDIR /app

RUN groupadd --system --gid 1000 app && \
    useradd --system --uid 1000 --gid app --no-create-home app

COPY --from=build /opt/venv /opt/venv
COPY --chown=app:app . .

USER app

EXPOSE 5000

CMD ["sh", "-c", "exec gunicorn --bind 0.0.0.0:${PORT} --workers 2 app:application"]
