# syntax=docker/dockerfile:1
# Generated by Anchor for a static (vite) app. Commit your own Dockerfile to take over.

# ── Build ───────────────────────────────────────────────────────────────
FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci && mkdir -p node_modules

COPY . .
RUN npm run build

# ── Runtime: unprivileged nginx listening on $PORT ──────────────────────
FROM nginxinc/nginx-unprivileged:1.27-alpine

USER root
RUN mkdir -p /etc/nginx/templates && \
    printf '%s\n' \
      'server {' \
      '  listen ${PORT};' \
      '  server_name _;' \
      '  server_tokens off;' \
      '  root /usr/share/nginx/html;' \
      '  index index.html;' \
      '  location / { try_files $uri $uri/ /index.html; }' \
      '}' > /etc/nginx/templates/default.conf.template
USER 101

COPY --from=build /app/dist /usr/share/nginx/html

ENV PORT=8080
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
