# syntax=docker/dockerfile:1
# Generated by Anchor for a Node.js app. Commit your own Dockerfile to take over.

# ── Dependencies ────────────────────────────────────────────────────────
FROM node:20.11.1-alpine AS deps

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production && mkdir -p node_modules

# ── Runtime ─────────────────────────────────────────────────────────────
FROM node:20.11.1-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production \
    HOST=0.0.0.0 \
    PORT=3000

COPY --from=deps --chown=node:node /app/node_modules ./node_modules
COPY --chown=node:node . .

USER node

EXPOSE 3000

CMD ["npm", "start"]
