# syntax=docker/dockerfile:1
# Generated by Anchor for a Django app. Commit your own Dockerfile to take over.

# ── Build: dependencies into a virtualenv ───────────────────────────────
FROM python:3.12-slim AS build

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:$PATH"

WORKDIR /app

RUN python -m venv /opt/venv

RUN python -m venv /opt/poetry && \
    /opt/poetry/bin/pip install --no-cache-dir "poetry>=1.8,<3"
ENV POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1
COPY pyproject.toml poetry.lock ./
RUN /opt/poetry/bin/poetry install --only main --no-root

# ── Runtime: non-root, venv + source only ───────────────────────────────
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:$PATH" \
    PORT=8000 \
    DJANGO_SETTINGS_MODULE=mysite.settings

WORKDIR /app

RUN groupadd --system --gid 1000 app && \
    useradd --system --uid 1000 --gid app --no-create-home app

COPY --from=build /opt/venv /opt/venv
COPY --chown=app:app . .

# Throwaway key: collectstatic imports settings but never signs anything.
RUN SECRET_KEY=collectstatic-only DJANGO_SECRET_KEY=collectstatic-only python manage.py collectstatic --noinput

USER app

EXPOSE 8000

CMD ["sh", "-c", "exec gunicorn --bind 0.0.0.0:${PORT} --workers 2 mysite.wsgi:application"]
