# syntax=docker/dockerfile:1
# Generated by Anchor for a static app. Commit your own Dockerfile to take over.

# ── Runtime: unprivileged nginx listening on $PORT ──────────────────────
FROM nginxinc/nginx-unprivileged:1.27-alpine

USER root
RUN mkdir -p /etc/nginx/templates && \
    printf '%s\n' \
      'server {' \
      '  listen ${PORT};' \
      '  server_name _;' \
      '  server_tokens off;' \
      '  root /usr/share/nginx/html;' \
      '  index index.html;' \
      '  location / { try_files $uri $uri/ =404; }' \
      '}' > /etc/nginx/templates/default.conf.template
USER 101

COPY . /usr/share/nginx/html

ENV PORT=8080
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
