# syntax=docker/dockerfile:1
# Generated by Anchor for a Phoenix app. Commit your own Dockerfile to take over.

# ── Build: compile a release ────────────────────────────────────────────
FROM hexpm/elixir:1.18.4-erlang-27.3.4.16-alpine-3.22.5 AS build

RUN apk add --no-cache build-base git

WORKDIR /app

ENV MIX_ENV=prod

RUN mix local.hex --force && mix local.rebar --force

COPY mix.exs mix.lock* ./
RUN mix deps.get --only prod

# Compile-time config must be present before dependencies compile.
COPY config config
RUN mix deps.compile

COPY . .
RUN mix assets.deploy
RUN mix compile && mix release

# ── Runtime: release only, non-root ─────────────────────────────────────
FROM alpine:3.22.5

RUN apk add --no-cache libstdc++ openssl ncurses-libs

WORKDIR /app

RUN addgroup -g 1000 elixir && adduser -u 1000 -G elixir -s /bin/sh -D elixir

COPY --from=build --chown=elixir:elixir /app/_build/prod/rel/hello ./

USER elixir:elixir

ENV PHX_SERVER=true \
    MIX_ENV=prod \
    PORT=4000
EXPOSE 4000

CMD ["bin/hello", "start"]
